In [1]:
import pandas as pd
import os
import numpy as np
data_path = '/Users/subashkhanal/Desktop/Lin_Lab/LinBrainLab/MLforMedicine/NACC/data/'
summary_path = '/Users/subashkhanal/Desktop/Lin_Lab/LinBrainLab/MLforMedicine/NACC/data/summary/'

df_uds = pd.read_csv(os.path.join(data_path,'lin10232020.csv'))
df_mri = pd.read_csv(os.path.join(data_path,'lin10232020mri.csv'))
len(set(df_uds['NACCID'])),len(set(df_mri['NACCID']))

/Users/subashkhanal/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (15,17,71,82,85,95,162,164,166,184,186,197,210,219,259,332,340,365,401,417,434,437,442,454,465,529,531,533,535,541,602,657,658,667,668,669,670,680,702,705) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

(2473, 2473)

In [2]:
len(df_uds),len(df_mri)

(15539, 4006)

In [3]:
from collections import Counter
Counter(df_uds['NACCUDSD'])

Counter({4: 3542, 1: 9000, 3: 2565, 2: 432})

In [4]:
print(set(df_uds['NACCID'])==set(df_mri['NACCID']))
print(set(df_uds['NACCADC'])==set(df_mri['NACCADC']))

True
True

Issue currently: There is no variable indicating diagnosis or even visit year in the MRI data provided('lin10232020mri.csv').Request for this information or have a rough estimate as a placeholder for now.

# Rough Estimate for diagnostic value

In [5]:
diag = []
for i in range(len(df_mri)):
    ID = df_mri.iloc[i]['NACCID']
    diag.append(round(df_uds[df_uds['NACCID']== ID]['NACCUDSD'].mean()))

In [6]:
smri = df_mri.loc[:,'NACCICV':'RTRTEMM']
smri['NACCID']= df_mri['NACCID']
smri['NACCUDSD'] = diag
smri = smri[(smri['NACCUDSD']==1)| (smri['NACCUDSD']==2) | (smri['NACCUDSD']==3)| (smri['NACCUDSD']==4)]
smri

,NACCICV,NACCBRNV,NACCWMVL,CSFVOL,GRAYVOL,WHITEVOL,WMHVOL,HIPPOVOL,CEREALL,CERETISS,...,RSUPPAR,RSUPPARM,RSUPTEM,RSUPTEMM,RSUPMAR,RSUPMARM,RTRTEM,RTRTEMM,NACCID,NACCUDSD
0,1317.832,1000.009,505.529,296.153,516.150,483.859,21.6695,5.2743,1151.75,900.071,...,9.1367,1.9972,11.5314,1.9698,9.3356,1.8527,0.7439,0.9281,NACC000225,2
1,1395.502,968.750,412.091,395.280,588.131,380.619,31.4715,5.5533,1205.02,873.852,...,10.7747,2.1556,12.4756,2.4000,10.2354,2.2747,0.8941,1.2468,NACC000225,2
2,1521.815,1049.548,470.486,461.390,589.939,459.609,10.8770,7.2404,1305.10,909.978,...,11.5499,2.5223,10.6344,1.4780,8.8320,1.8634,0.7214,1.3035,NACC000546,4
3,1440.846,1152.588,506.359,286.419,648.068,504.520,1.8389,6.4687,1232.34,1004.860,...,11.2978,1.7909,18.4463,2.6488,9.2725,2.0544,1.2012,1.9094,NACC000920,1
4,1397.713,1115.268,492.037,280.659,625.017,490.251,1.7864,6.3123,1201.31,973.187,...,11.0522,1.6348,17.4270,2.3667,9.3948,1.7884,1.1173,1.6261,NACC000920,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4001,1279.144,1029.621,423.873,247.755,607.516,422.105,1.7676,6.0000,1073.75,871.057,...,10.1709,1.5900,13.0488,2.4005,8.6699,1.8684,0.9707,1.3460,NACC998980,2
4002,1283.366,1025.085,437.692,254.097,591.577,433.508,4.1836,5.7617,1075.04,868.925,...,10.0117,1.4120,13.0498,2.2127,8.4531,1.7180,1.0469,1.4196,NACC998980,2
4003,1499.863,1047.882,436.386,447.690,615.787,432.095,4.2905,6.1520,1287.05,900.290,...,10.9688,1.2888,12.8493,1.9068,8.4934,1.8034,0.8321,1.0659,NACC999346,4
4004,1722.800,1248.570,508.970,462.230,751.600,496.970,12.0000,5.2800,1500.94,1105.430,...,13.1200,1.4100,16.5900,2.0300,10.8200,1.7900,1.2400,1.4700,NACC999780,3
4005,9999.999,952.406,9999.999,310.973,540.207,412.199,999.9999,6.3803,1088.02,828.506,...,12.1195,1.8126,11.8349,1.9515,10.7952,1.9688,0.8625,1.7454,NACC999854,1

In [7]:
summary = smri.describe()
summary

,NACCICV,NACCBRNV,NACCWMVL,CSFVOL,GRAYVOL,WHITEVOL,WMHVOL,HIPPOVOL,CEREALL,CERETISS,...,RSUPFRM,RSUPPAR,RSUPPARM,RSUPTEM,RSUPTEMM,RSUPMAR,RSUPMARM,RTRTEM,RTRTEMM,NACCUDSD
count,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,...,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000
mean,2834.051137,1020.073224,2065.558029,352.639826,581.060125,439.013099,176.838214,6.084803,1182.955723,889.125365,...,2.191271,10.306404,1.455714,13.419151,2.154542,8.543447,1.787059,0.837666,1.401645,2.128308
std,3240.466512,113.054555,3585.329064,64.464293,63.393543,60.904362,372.114851,0.949684,130.263508,99.840163,...,0.336723,1.779840,0.295357,1.899603,0.354509,1.575618,0.288697,0.245566,0.391752,1.249025
min,956.372000,659.178000,269.770000,185.855000,330.807000,248.950000,0.000000,0.957700,822.075000,605.504000,...,0.845200,4.245700,0.377800,6.990000,0.864700,3.237000,0.719200,0.248000,0.386600,1.000000
25%,1287.715500,943.058750,411.953500,305.146750,537.721250,396.071750,1.570000,5.489000,1091.012500,820.056250,...,1.991725,9.079550,1.261350,12.170000,1.944125,7.437400,1.600225,0.670600,1.101775,1.000000
50%,1403.052000,1011.370500,458.610000,349.520000,579.254000,435.020500,5.631000,6.120700,1177.095000,882.023000,...,2.190000,10.234950,1.450450,13.360000,2.145700,8.457000,1.791600,0.815400,1.430000,2.000000
75%,1569.296000,1092.719250,525.115750,394.139000,622.626250,477.486500,23.889600,6.746450,1267.955000,951.811500,...,2.378375,11.428500,1.637800,14.639900,2.369900,9.578400,1.968750,0.977925,1.683100,3.000000
max,9999.999000,1429.340000,9999.999000,633.365000,824.030000,693.520000,999.999900,9.180000,1639.250000,1266.500000,...,4.060000,17.318000,3.199600,21.300000,5.040000,14.677000,3.438300,2.070000,3.068900,4.000000

After close inspection of the max values for each feature it is found that only three columns have missing values

'NACCICV':9999.999 

'NACCWMVL':9999.999 

'WMHVOL':999.9999 

Now let's replace these fields with np.nan so that our algorithms later will deal with them in standard way

In [8]:
smri_final = smri.copy()
smri_final.loc[(smri_final['NACCICV']== 9999.999) | (smri_final['NACCICV']== 8888.888),'NACCICV']= np.nan
smri_final.loc[(smri_final['NACCWMVL']== 9999.999) | (smri_final['NACCWMVL']== 8888.888),'NACCWMVL']= np.nan
smri_final.loc[(smri_final['WMHVOL']== 999.9999) | (smri_final['WMHVOL']== 888.8888),'WMHVOL']= np.nan

In [9]:
smri_final.describe()

,NACCICV,NACCBRNV,NACCWMVL,CSFVOL,GRAYVOL,WHITEVOL,WMHVOL,HIPPOVOL,CEREALL,CERETISS,...,RSUPFRM,RSUPPAR,RSUPPARM,RSUPTEM,RSUPTEMM,RSUPMAR,RSUPMARM,RTRTEM,RTRTEMM,NACCUDSD
count,3327.000000,4006.000000,3327.000000,4006.000000,4006.000000,4006.000000,3327.000000,4006.000000,4006.000000,4006.000000,...,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000,4006.000000
mean,1371.568841,1020.073224,446.235690,352.639826,581.060125,439.013099,8.840984,6.084803,1182.955723,889.125365,...,2.191271,10.306404,1.455714,13.419151,2.154542,8.543447,1.787059,0.837666,1.401645,2.128308
std,146.955474,113.054555,59.690475,64.464293,63.393543,60.904362,13.261433,0.949684,130.263508,99.840163,...,0.336723,1.779840,0.295357,1.899603,0.354509,1.575618,0.288697,0.245566,0.391752,1.249025
min,956.372000,659.178000,269.770000,185.855000,330.807000,248.950000,0.000000,0.957700,822.075000,605.504000,...,0.845200,4.245700,0.377800,6.990000,0.864700,3.237000,0.719200,0.248000,0.386600,1.000000
25%,1268.440000,943.058750,403.730500,305.146750,537.721250,396.071750,1.199250,5.489000,1091.012500,820.056250,...,1.991725,9.079550,1.261350,12.170000,1.944125,7.437400,1.600225,0.670600,1.101775,1.000000
50%,1360.659000,1011.370500,442.850000,349.520000,579.254000,435.020500,3.850000,6.120700,1177.095000,882.023000,...,2.190000,10.234950,1.450450,13.360000,2.145700,8.457000,1.791600,0.815400,1.430000,2.000000
75%,1469.410000,1092.719250,484.376500,394.139000,622.626250,477.486500,10.640000,6.746450,1267.955000,951.811500,...,2.378375,11.428500,1.637800,14.639900,2.369900,9.578400,1.968750,0.977925,1.683100,3.000000
max,1906.674000,1429.340000,695.390000,633.365000,824.030000,693.520000,132.840000,9.180000,1639.250000,1266.500000,...,4.060000,17.318000,3.199600,21.300000,5.040000,14.677000,3.438300,2.070000,3.068900,4.000000

In [10]:
smri_final

,NACCICV,NACCBRNV,NACCWMVL,CSFVOL,GRAYVOL,WHITEVOL,WMHVOL,HIPPOVOL,CEREALL,CERETISS,...,RSUPPAR,RSUPPARM,RSUPTEM,RSUPTEMM,RSUPMAR,RSUPMARM,RTRTEM,RTRTEMM,NACCID,NACCUDSD
0,1317.832,1000.009,505.529,296.153,516.150,483.859,21.6695,5.2743,1151.75,900.071,...,9.1367,1.9972,11.5314,1.9698,9.3356,1.8527,0.7439,0.9281,NACC000225,2
1,1395.502,968.750,412.091,395.280,588.131,380.619,31.4715,5.5533,1205.02,873.852,...,10.7747,2.1556,12.4756,2.4000,10.2354,2.2747,0.8941,1.2468,NACC000225,2
2,1521.815,1049.548,470.486,461.390,589.939,459.609,10.8770,7.2404,1305.10,909.978,...,11.5499,2.5223,10.6344,1.4780,8.8320,1.8634,0.7214,1.3035,NACC000546,4
3,1440.846,1152.588,506.359,286.419,648.068,504.520,1.8389,6.4687,1232.34,1004.860,...,11.2978,1.7909,18.4463,2.6488,9.2725,2.0544,1.2012,1.9094,NACC000920,1
4,1397.713,1115.268,492.037,280.659,625.017,490.251,1.7864,6.3123,1201.31,973.187,...,11.0522,1.6348,17.4270,2.3667,9.3948,1.7884,1.1173,1.6261,NACC000920,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4001,1279.144,1029.621,423.873,247.755,607.516,422.105,1.7676,6.0000,1073.75,871.057,...,10.1709,1.5900,13.0488,2.4005,8.6699,1.8684,0.9707,1.3460,NACC998980,2
4002,1283.366,1025.085,437.692,254.097,591.577,433.508,4.1836,5.7617,1075.04,868.925,...,10.0117,1.4120,13.0498,2.2127,8.4531,1.7180,1.0469,1.4196,NACC998980,2
4003,1499.863,1047.882,436.386,447.690,615.787,432.095,4.2905,6.1520,1287.05,900.290,...,10.9688,1.2888,12.8493,1.9068,8.4934,1.8034,0.8321,1.0659,NACC999346,4
4004,1722.800,1248.570,508.970,462.230,751.600,496.970,12.0000,5.2800,1500.94,1105.430,...,13.1200,1.4100,16.5900,2.0300,10.8200,1.7900,1.2400,1.4700,NACC999780,3
4005,NaN,952.406,NaN,310.973,540.207,412.199,NaN,6.3803,1088.02,828.506,...,12.1195,1.8126,11.8349,1.9515,10.7952,1.9688,0.8625,1.7454,NACC999854,1

# Replace NaN with mean for that column

In [11]:
smri_final[['NACCICV']] = smri_final[['NACCICV']].fillna(value=smri_final.NACCICV.mean())
smri_final[['NACCWMVL']] = smri_final[['NACCWMVL']].fillna(value=smri_final.NACCWMVL.mean())
smri_final[['WMHVOL']] = smri_final[['WMHVOL']].fillna(value=smri_final.NACCICV.mean())

In [12]:
smri_final.isnull().sum().sum() #check if NaNs left?

0

In [13]:
#smri_final['NACCMMSE'] = np.nan

In [14]:
smri_final.to_csv(os.path.join(data_path,'lin10232020mri_diag.csv'))